# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: ./
    restart: always
    ports:
      - 8082:8082
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ratusanlimadadakandigorengbulattahu